# Site settings
name: Gurvansh Gupta
title: Gurvansh Gupta | Software Development Engineer
description: I am a software development engineer with a passion for building scalable and efficient systems.
url: https://gurvanshgupta.github.io/
baseurl: ''
email: dev.gurvansh.gupta@gmail.com
cover: https://gurvanshgupta.github.io/img/og.png
logo: https://gurvanshgupta.github.io/img/emojis/technologist.png
resume: https://gurvanshgupta.github.io/resume.pdf
social:
  - title: email
    url: dev.gurvansh.gupta@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/Obsidian-Ninja
  - title: linkedin
    url: https://www.linkedin.com/in/gurvansh-gupta-b19550289/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
